import { Task } from "@/lib/types";

export const tasks: Task[] = [
  {
    id: "1",
    title: "Subscription Table UI",
    description: "Design and implement subscription table with filters",
    projectId: "1",
    projectName: "TapZio Website",
    priority: "high",
    status: "in_progress",
    deadline: "2026-07-26T23:59:00",
    deadlineLabel: "Today",
    iconColor: "green",
    progress: 70,
    createdAt: "2026-07-20",
    taskType: "Development",
    estimatedTime: "8h",
    spentTime: "5h 30m",
    attachments: [
      { id: "1", name: "table-design.png", size: "245 KB", type: "image/png" },
    ],
  },
  {
    id: "2",
    title: "API Integration",
    description: "API integration for subscription management",
    projectId: "1",
    projectName: "TapZio Website",
    priority: "high",
    status: "in_progress",
    deadline: "2026-07-28",
    deadlineLabel: "28 Jul",
    iconColor: "orange",
    progress: 55,
    createdAt: "2026-07-18",
    taskType: "Development",
    estimatedTime: "12h",
    spentTime: "6h 45m",
  },
  {
    id: "3",
    title: "Payment Gateway UI",
    description: "Design payment flow screens",
    projectId: "1",
    projectName: "TapZio Website",
    priority: "medium",
    status: "review",
    deadline: "2026-07-30",
    progress: 90,
    createdAt: "2026-07-15",
    taskType: "Design",
    estimatedTime: "6h",
    spentTime: "5h 20m",
  },
  {
    id: "4",
    title: "Dashboard Wireframes",
    description: "Create wireframes for ERP dashboard",
    projectId: "2",
    projectName: "ERP System",
    priority: "medium",
    status: "in_progress",
    deadline: "2026-08-01",
    progress: 40,
    createdAt: "2026-07-10",
    taskType: "Design",
    estimatedTime: "10h",
    spentTime: "4h",
  },
  {
    id: "5",
    title: "User Role Management",
    description: "Design user role and permission management",
    projectId: "2",
    projectName: "ERP System",
    priority: "medium",
    status: "todo",
    deadline: "2026-07-30",
    deadlineLabel: "30 Jul",
    iconColor: "blue",
    progress: 0,
    createdAt: "2026-07-22",
    taskType: "Design",
    estimatedTime: "4h",
    spentTime: "0h",
  },
  {
    id: "6",
    title: "Onboarding Flow",
    description: "Design app onboarding screens",
    projectId: "3",
    projectName: "Mobile App UI",
    priority: "medium",
    status: "todo",
    deadline: "2026-08-10",
    progress: 0,
    createdAt: "2026-07-23",
    taskType: "Design",
    estimatedTime: "8h",
    spentTime: "0h",
  },
  {
    id: "7",
    title: "Logo Variations",
    description: "Create logo variations for brand",
    projectId: "4",
    projectName: "Brand Identity",
    priority: "low",
    status: "in_progress",
    deadline: "2026-08-15",
    progress: 30,
    createdAt: "2026-07-01",
    taskType: "Design",
    estimatedTime: "5h",
    spentTime: "1h 30m",
  },
  {
    id: "8",
    title: "Hero Section Design",
    description: "Landing page hero section",
    projectId: "5",
    projectName: "Landing Page",
    priority: "high",
    status: "completed",
    deadline: "2026-07-10",
    progress: 100,
    createdAt: "2026-06-25",
    taskType: "Design",
    estimatedTime: "6h",
    spentTime: "6h",
  },
];

export const taskStats = {
  total: 8,
  todo: 2,
  inProgress: 4,
  review: 1,
  completed: 1,
};
